import Navbar from "@components/Navbar";
import Sidebar from "@components/Sidebar";
import "@styles/globals.css";
import { Providers } from "../GlobalRedux/provider";
import ScrollButton from "@components/ScrollButton";
import React from "react";

export const metadata = {
  title: "Website",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  eventModal,
}: {
  children: React.ReactNode;
  eventModal: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          {eventModal}
          <Navbar />
          <Sidebar />
          <div className='ml-[60px] lg:ml-[200px] flex flex-col'>
            <div className='mt-[60px] pt-5 bg-gray-800'>{children}</div>
          </div>
          <ScrollButton />
        </Providers>
      </body>
    </html>
  );
}
